spring.application.name=infom-systems-lab1

spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.url=${DB_URL}
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

spring.datasource.druid.initial-size=3
spring.datasource.druid.min-idle=3
spring.datasource.druid.max-active=20
spring.datasource.druid.max-wait=60000
spring.datasource.druid.time-between-eviction-runs-millis=60000
spring.datasource.druid.min-evictable-idle-time-millis=300000
spring.datasource.druid.validation-query=SELECT 1
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
spring.datasource.druid.pool-prepared-statements=true
spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20
spring.datasource.druid.filters=stat,slf4j
spring.datasource.druid.filter.stat.merge-sql=true
spring.datasource.druid.filter.stat.slow-sql-millis=500

spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform
spring.jpa.properties.eclipselink.weaving=false
spring.jpa.properties.eclipselink.logging.level=INFO
spring.jpa.properties.eclipselink.target-database=PostgreSQL
spring.jpa.properties.eclipselink.cache.shared.default=true
spring.jpa.properties.eclipselink.cache.size.default=500
spring.jpa.open-in-view=false
server.port=7000

spring.cache.jcache.config=classpath:ehcache.xml
cache.stats.logging-enabled=false

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=import-files

spring.sql.init.mode=never

jobs.import-recovery.stale-duration=PT10M
jobs.import-recovery.delay-ms=300000
default-lock-at-most-for=PT1M
