CREATE TABLE coordinates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    x FLOAT NOT NULL,
    y DOUBLE PRECISION NOT NULL
);

CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    x FLOAT NOT NULL,
    y INT NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    name VARCHAR(255) NOT NULL,
    eye_color VARCHAR(32),
    hair_color VARCHAR(32),
    location_id BIGINT,
    passportid VARCHAR(255),
    nationality VARCHAR(32),
    CONSTRAINT fk_person_location FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    name VARCHAR(255) NOT NULL,
    coordinates_id BIGINT NOT NULL,
    creation_date TIMESTAMP,
    oscars_count BIGINT,
    budget FLOAT,
    total_box_office BIGINT,
    mpaa_rating VARCHAR(16) NOT NULL,
    person_id BIGINT NOT NULL,
    screenwriter_id BIGINT,
    operator_id BIGINT NOT NULL,
    length INT,
    golden_palm_count BIGINT NOT NULL,
    usa_box_office BIGINT,
    genre VARCHAR(32) NOT NULL,
    CONSTRAINT fk_movie_coordinates FOREIGN KEY (coordinates_id) REFERENCES coordinates(id),
    CONSTRAINT fk_movie_director FOREIGN KEY (person_id) REFERENCES person(id),
    CONSTRAINT fk_movie_screenwriter FOREIGN KEY (screenwriter_id) REFERENCES person(id),
    CONSTRAINT fk_movie_operator FOREIGN KEY (operator_id) REFERENCES person(id)
);

CREATE TABLE import_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32),
    user_name VARCHAR(255) NOT NULL,
    IMPORTEDCOUNT INT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FILEKEY VARCHAR(512),
    TEMPFILEKEY VARCHAR(512),
    FILENAME VARCHAR(255),
    FILESIZE BIGINT
);
